//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 192.145639 on Stable branch
// Generated with ALiVE version 1.10.0.1904051
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class TALAG_O_WDL {
            name = "Talon Aegis (WDL)";

            class Infantry {
                name = "Infantry";

                class TALAG_O_WDL_RIFLESQUAD {
                    name = "Rifleman Squad";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AUTORIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_WEAPSQUAD {
                    name = "Weapons Squad";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AUTORIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_GRENADIER";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_REINSQUAD {
                    name = "Reinforcement Squad";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_MARKSQUAD {
                    name = "Marksman Squad";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_HVYMARKSMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_HVYMARKSMAN";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AMMARKSMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DESIGMARKSMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DESIGMARKSMAN";
                    };
                };

                class TALAG_O_WDL_SMGSQUAD {
                    name = "Static MG Squad";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MGWSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MGAWSPECIALIST";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_SATSQUAD {
                    name = "Static AT Squad";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATWSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATAWSPECIALIST";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                };

                class TALAG_O_WDL_ATSQUAD {
                    name = "AT Squad";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATSPECIALIST";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                };

                class TALAG_O_WDL_AASQUAD {
                    name = "AA Squad";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AASPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AASPECIALIST";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                };

                class TALAG_O_WDL_MGSQUAD {
                    name = "MG Squad";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MGSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AMGSPECIALIST";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AUTORIFLEMAN";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_SENTRY {
                    name = "Sentry";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_FIRETEAM {
                    name = "Fireteam";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AUTORIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DESIGMARKSMAN";
                    };
                };

                class TALAG_O_WDL_MGTEAM {
                    name = "MG Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AUTORIFLEMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MGSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AMGSPECIALIST";
                    };
                };

                class TALAG_O_WDL_ATTEAM {
                    name = "AT Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATSPECIALIST";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                };

                class TALAG_O_WDL_AATEAM {
                    name = "AA Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AASPECIALIST";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AASPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AASPECIALIST";
                    };
                };

                class TALAG_O_WDL_ASSTEAM {
                    name = "Assault Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_GRENADIER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_BREACHER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_BREACHER";
                    };
                };

                class TALAG_O_WDL_ASSSQUAD {
                    name = "Assault Squad";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_GRENADIER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_BREACHER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class TALAG_O_WDL_SNPTEAM {
                    name = "Sniper Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_SNIPER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_SNIPER";
                    };
                };

                class TALAG_O_WDL_RECTEAM {
                    name = "Recon Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RECOPERATIVE";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RECOPERATIVE";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RECOPERATIVE";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RECOPERATIVE";
                    };
                };

                class TALAG_O_WDL_PARA4M {
                    name = "Paratroopers (4 Man)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                };

                class TALAG_O_WDL_PARA6M {
                    name = "Paratroopers (6 Man)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                };

                class TALAG_O_WDL_PARA8M {
                    name = "Paratroopers (8 Man)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                };

                class TALAG_O_WDL_PARA10M {
                    name = "Paratroopers (10 Man)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_PARATROOPER";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class TALAG_O_L_WDL_PATHMMWV {
                    name = "Patrol (HMMWV)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit1 {
                        position[] = {5,-8,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_HMMWVM2";
                    };
                    class Unit2 {
                        position[] = {-5,-8,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_PATUAZ {
                    name = "Patrol (UAZ)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_UAZ";
                    };
                    class Unit2 {
                        position[] = {-5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit5 {
                        position[] = {15,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_MOTTEAMSF {
                    name = "Motorized Team (SF)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RECOPERATIVE";
                    };
                    class Unit1 {
                        position[] = {5,-7,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MRZR4";
                    };
                    class Unit2 {
                        position[] = {-5,-7,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RECOPERATIVE";
                    };
                    class Unit3 {
                        position[] = {10,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RECOPERATIVE";
                    };
                };

                class TALAG_O_WDL_MOTSQUADSF {
                    name = "Motorized Squad (SF)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RECOPERATIVE";
                    };
                    class Unit1 {
                        position[] = {5,-7,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MRZR4";
                    };
                    class Unit2 {
                        position[] = {-5,-7,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RECOPERATIVE";
                    };
                    class Unit3 {
                        position[] = {10,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RECOPERATIVE";
                    };
                    class Unit4 {
                        position[] = {-10,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RECOPERATIVE";
                    };
                    class Unit5 {
                        position[] = {15,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RECOPERATIVE";
                    };
                };

                class TALAG_O_WDL_MOTSQUADHMMWV {
                    name = "Motorized Squad (HMMWV)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {6,-8,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_HMMWVTRANS";
                    };
                    class Unit2 {
                        position[] = {-6,-8,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit3 {
                        position[] = {11,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AUTORIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-11,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit5 {
                        position[] = {16,-18,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-16,-18,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {21,-23,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_MOTSQUADKAMAZ {
                    name = "Motorized Squad (KamAZ)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {6,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_KAMAZ";
                    };
                    class Unit2 {
                        position[] = {-6,-24,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit3 {
                        position[] = {11,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AUTORIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-11,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_GRENADIER";
                    };
                    class Unit5 {
                        position[] = {16,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DESIGMARKSMAN";
                    };
                    class Unit6 {
                        position[] = {-16,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit7 {
                        position[] = {21,-39,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit8 {
                        position[] = {-21,-39,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MGSPECIALIST";
                    };
                    class Unit9 {
                        position[] = {26,-44,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AMGSPECIALIST";
                    };
                    class Unit10 {
                        position[] = {-26,-44,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DEMOMAN";
                    };
                    class Unit11 {
                        position[] = {31,-49,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ENGINEER";
                    };
                    class Unit12 {
                        position[] = {-31,-49,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit13 {
                        position[] = {36,-54,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit14 {
                        position[] = {-36,-54,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit15 {
                        position[] = {41,-59,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit16 {
                        position[] = {-41,-59,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

                class TALAG_O_WDL_COMMTEAM {
                    name = "Commissar Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_OFFICER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_MEDTEAM {
                    name = "Medical Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                };

                class TALAG_O_WDL_DEMOTEAM {
                    name = "Demolition Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DEMOMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DEMOMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DEMOMAN";
                    };
                };

                class TALAG_O_WDL_ENGIETEAM {
                    name = "Engineering Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ENGINEER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ENGINEER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ENGINEER";
                    };
                };

                class TALAG_O_WDL_SMGTEAM {
                    name = "Static MG Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AUTORIFLEMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MGWSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MGAWSPECIALIST";
                    };
                };

                class TALAG_O_WDL_SATTEAM {
                    name = "Static AT Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATSPECIALIST";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATWSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATAWSPECIALIST";
                    };
                };

                class TALAG_O_WDL_MOTTEAM {
                    name = "Motar Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_GRENADIER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MOTWSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MOTAWSPECIALIST";
                    };
                };

                class TALAG_O_WDL_MARKTEAM {
                    name = "Marksman Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_HVYMARKSMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DESIGMARKSMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DESIGMARKSMAN";
                    };
                };

                class TALAG_O_WDL_HVYMARKTEAM {
                    name = "Heavy Marksman Team";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AMMARKSMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_HVYMARKSMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_HVYMARKSMAN";
                    };
                };

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class TALAG_O_WDL_MECHSQUADM113A3 {
                    name = "Mechanized Squad (M113A3)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {7,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_M113A3M2";
                    };
                    class Unit2 {
                        position[] = {-7,-9,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit3 {
                        position[] = {12,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AUTORIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-12,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_GRENADIER";
                    };
                    class Unit5 {
                        position[] = {17,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DESIGMARKSMAN";
                    };
                    class Unit6 {
                        position[] = {-17,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit7 {
                        position[] = {22,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MGSPECIALIST";
                    };
                    class Unit8 {
                        position[] = {-22,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AMGSPECIALIST";
                    };
                    class Unit9 {
                        position[] = {27,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit10 {
                        position[] = {-27,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit11 {
                        position[] = {32,-34,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_MECHSQUADBTR60 {
                    name = "Mechanized Squad (BTR60)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {9,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_BTR60PB";
                    };
                    class Unit2 {
                        position[] = {-9,-12,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit3 {
                        position[] = {14,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AUTORIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-14,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_GRENADIER";
                    };
                    class Unit5 {
                        position[] = {19,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DESIGMARKSMAN";
                    };
                    class Unit6 {
                        position[] = {-19,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit7 {
                        position[] = {24,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MGSPECIALIST";
                    };
                    class Unit8 {
                        position[] = {-24,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AMGSPECIALIST";
                    };
                    class Unit9 {
                        position[] = {29,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit10 {
                        position[] = {-29,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit11 {
                        position[] = {34,-37,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit12 {
                        position[] = {-34,-37,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit13 {
                        position[] = {39,-42,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit14 {
                        position[] = {-39,-42,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_MECHSQUADBMP2 {
                    name = "Mechanized Squad (BMP2)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {8,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_BMP2";
                    };
                    class Unit2 {
                        position[] = {-8,-12,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit3 {
                        position[] = {13,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AUTORIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-13,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_GRENADIER";
                    };
                    class Unit5 {
                        position[] = {18,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DESIGMARKSMAN";
                    };
                    class Unit6 {
                        position[] = {-18,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit7 {
                        position[] = {23,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MGSPECIALIST";
                    };
                    class Unit8 {
                        position[] = {-23,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AMGSPECIALIST";
                    };
                    class Unit9 {
                        position[] = {28,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATSPECIALIST";
                    };
                    class Unit10 {
                        position[] = {-28,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit11 {
                        position[] = {33,-37,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_MECHSQUADMTLB {
                    name = "Mechanized Squad (MT-LB)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {8,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MTLBLV";
                    };
                    class Unit2 {
                        position[] = {-8,-12,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit3 {
                        position[] = {13,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_AUTORIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-13,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_GRENADIER";
                    };
                    class Unit5 {
                        position[] = {18,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DESIGMARKSMAN";
                    };
                    class Unit6 {
                        position[] = {-18,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit7 {
                        position[] = {23,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit8 {
                        position[] = {-23,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                    class Unit9 {
                        position[] = {28,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RIFLEMAN";
                    };
                };

                class TALAG_O_WDL_MECHSQUADM60A3 {
                    name = "Mechanized Squad (M60A3)";
                    side = 0;
                    faction = "TALAG_O_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WDL_LEADER";
                    };
                    class Unit1 {
                        position[] = {9,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_M60A3";
                    };
                    class Unit2 {
                        position[] = {-9,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WDL_RTO";
                    };
                    class Unit3 {
                        position[] = {14,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ATRIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-14,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_MEDIC";
                    };
                    class Unit5 {
                        position[] = {19,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_ENGINEER";
                    };
                    class Unit6 {
                        position[] = {-19,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WDL_DEMOMAN";
                    };
                };

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};