//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 194.145977 on Stable branch
// Generated with ALiVE version 1.11.3.1905291
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class TA_O_DES {
        displayName = "Talon Aegis (DES)";
        side = 0;
        flag = "x\cfp\addons\flags\Others\3percenters.paa";
        icon = "x\cfp\addons\flags\Others\3percenters.paa";
        priority = 0;
    };
};