//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 192.145639 on Stable branch
// Generated with ALiVE version 1.10.0.1904051
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class TALAG_O_WNT {
        displayName = "Talon Aegis (WNT)";
        side = 0;
        flag = "x\cfp\addons\flags\Others\3percenters.paa";
        icon = "x\cfp\addons\flags\Others\3percenters.paa";
        priority = 0;
    };
};