//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 192.145639 on Stable branch
// Generated with ALiVE version 1.10.0.1904051
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class TALAG_O_WNT {
            name = "Talon Aegis (WNT)";

            class Infantry {
                name = "Infantry";

                class TALAG_O_WNT_RIFLEMANSQUAD {
                    name = "Rifleman Squad";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AUTORIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_WEAPSQUAD {
                    name = "Weapons Squad";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AUTORIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_GRENADIER";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_REINSQUAD {
                    name = "Reinforcement Squad";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_MARKSQUAD {
                    name = "Marksman Squad";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_HMARKSMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_HMARKSMAN";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AMMARKSMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_DESIGMARKSMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_DESIGMARKSMAN";
                    };
                };

                class TALAG_O_WNT_SMGSQUAD {
                    name = "Static MG Squad";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MGWSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MGAWSPECIALIST";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_SATSQUAD {
                    name = "Static AT Squad";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATWSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATAWSPECIALIST";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                };

                class TALAG_O_WNT_AASQUAD {
                    name = "AA Squad";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AASPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AASPECIALIST";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                };

                class TALAG_O_WNT_ATSQUAD {
                    name = "AT Squad";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATSPECIALIST";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                };

                class TALAG_O_WNT_MGSQUAD {
                    name = "MG Squad";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MGSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AMGSPECIALIST";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AUTORIFLEMAN";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_SENTRY {
                    name = "Sentry";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_FIRETEAM {
                    name = "Fireteam";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AUTORIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_DESIGMARKSMAN";
                    };
                };

                class TALAG_O_WNT_MGTEAM {
                    name = "MG Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AUTORIFLEMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MGSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AMGSPECIALIST";
                    };
                };

                class TALAG_O_WNT_ATTEAM {
                    name = "AT Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATSPECIALIST";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                };

                class TALAG_O_WNT_AATEAM {
                    name = "AA Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AASPECIALIST";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AASPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AASPECIALIST";
                    };
                };

                class TALAG_O_WNT_ASSTEAM {
                    name = "Assault Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_GRENADIER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_BREACHER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_BREACHER";
                    };
                };

                class TALAG_O_WNT_ASSSQUAD {
                    name = "Assault Squad";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_GRENADIER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_BREACHER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class TALAG_O_WNT_SNPTEAM {
                    name = "Sniper Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_SNIPER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_SNIPER";
                    };
                };

                class TALAG_O_WNT_RECTEAM {
                    name = "Recon Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                };

                class TALAG_O_WNT_PARA4M {
                    name = "Paratroopers (4 Man)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                };

                class TALAG_O_WNT_PARA6M {
                    name = "Paratroopers (6 Man)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                };

                class TALAG_O_WNT_PARA8M {
                    name = "Paratroopers (8 Man)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                };

                class TALAG_O_WNT_PARA10M {
                    name = "Paratroopers (10 Man)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_PARATROOPER";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class TALAG_O_WNT_PATJEEP {
                    name = "Patrol (Jeep)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_JEEP";
                    };
                    class Unit2 {
                        position[] = {-5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_PATMATV {
                    name = "Patrol (M-ATV)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit1 {
                        position[] = {5,-14,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MATV";
                    };
                    class Unit2 {
                        position[] = {-5,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_MOTTEAMSF {
                    name = "Motorized Team (SF)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_QUILIN";
                    };
                    class Unit2 {
                        position[] = {-5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit3 {
                        position[] = {10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                };

                class TALAG_O_WNT_MOTSQUADSF {
                    name = "Motorized Squad (SF)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_QUILIN";
                    };
                    class Unit2 {
                        position[] = {-5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit3 {
                        position[] = {10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit4 {
                        position[] = {-10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit5 {
                        position[] = {15,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit6 {
                        position[] = {-15,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                };

                class TALAG_O_WNT_MOTSQUADRG31 {
                    name = "Motorized Squad (RG-31)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RG31";
                    };
                    class Unit2 {
                        position[] = {-5,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit3 {
                        position[] = {10,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit4 {
                        position[] = {-10,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit5 {
                        position[] = {15,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit6 {
                        position[] = {-15,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_MOTSQUADRG31MK5E {
                    name = "Motorized Squad (RG-31 Mk5E)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {5,-11,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RG31MK5E";
                    };
                    class Unit2 {
                        position[] = {-5,-11,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit3 {
                        position[] = {10,-16,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-10,-16,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AUTORIFLEMAN";
                    };
                    class Unit5 {
                        position[] = {15,-21,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit6 {
                        position[] = {-15,-21,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit7 {
                        position[] = {20,-26,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit8 {
                        position[] = {-20,-26,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_MOTSQUADSFAT {
                    name = "Motorized Squad (SF/AT)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATQUILIN";
                    };
                    class Unit2 {
                        position[] = {-5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit3 {
                        position[] = {10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit4 {
                        position[] = {-10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit5 {
                        position[] = {15,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                };

                class TALAG_O_WNT_MOTSQUADSFMG {
                    name = "Motorized Squad (SF/MG)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MGQUILIN";
                    };
                    class Unit2 {
                        position[] = {-5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit3 {
                        position[] = {10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit4 {
                        position[] = {-10,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                    class Unit5 {
                        position[] = {15,-19,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RECOPERATOR";
                    };
                };

                class TALAG_O_WNT_MOTSQUADURAL {
                    name = "Motorized Squad (Ural)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {6,-13,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_URAL";
                    };
                    class Unit2 {
                        position[] = {-6,-13,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit3 {
                        position[] = {11,-18,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AUTORIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-11,-18,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_GRENADIER";
                    };
                    class Unit5 {
                        position[] = {16,-23,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_DESIGMARKSMAN";
                    };
                    class Unit6 {
                        position[] = {-16,-23,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit7 {
                        position[] = {21,-28,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MGSPECIALIST";
                    };
                    class Unit8 {
                        position[] = {-21,-28,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AMGSPECIALIST";
                    };
                    class Unit9 {
                        position[] = {26,-33,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit10 {
                        position[] = {-26,-33,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit11 {
                        position[] = {31,-38,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit12 {
                        position[] = {-31,-38,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit13 {
                        position[] = {36,-43,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit14 {
                        position[] = {-36,-43,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

                class TALAG_O_WNT_COMMTEAM {
                    name = "Commissar Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_OFFICER";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_MEDTEAM {
                    name = "Medical Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                };

                class TALAG_O_WNT_DEMOTEAM {
                    name = "Demolition Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_DEMOMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_DEMOMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_DEMOMAN";
                    };
                };

                class TALAG_O_WNT_ENGIETEAM {
                    name = "Engineering Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ENGINEER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ENGINEER";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ENGINEER";
                    };
                };

                class TALAG_O_WNT_SMGTEAM {
                    name = "Static MG Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AUTORIFLEMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MGWSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MGAWSPECIALIST";
                    };
                };

                class TALAG_O_WNT_SATTEAM {
                    name = "Static AT Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATSPECIALIST";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATWSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATAWSPECIALIST";
                    };
                };

                class TALAG_O_WNT_MOTTEAM {
                    name = "Motar Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_GRENADIER";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MOTWSPECIALIST";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MOTAWSPECIALIST";
                    };
                };

                class TALAG_O_WNT_MARKTEAM {
                    name = "Marksman Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_HMARKSMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_DESIGMARKSMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_DESIGMARKSMAN";
                    };
                };

                class TALAG_O_WTN_HMARKTEAM {
                    name = "Heavy Marksman Team";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AMMARKSMAN";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_HMARKSMAN";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_HMARKSMAN";
                    };
                };

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class TALAG_O_WNT_MECHSQUADBTR60PB {
                    name = "Mechanized Squad (BTR60PB)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {9,-12,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_BTR60PB";
                    };
                    class Unit2 {
                        position[] = {-9,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit3 {
                        position[] = {14,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AUTORIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-14,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_GRENADIER";
                    };
                    class Unit5 {
                        position[] = {19,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_DESIGMARKSMAN";
                    };
                    class Unit6 {
                        position[] = {-19,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit7 {
                        position[] = {24,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MGSPECIALIST";
                    };
                    class Unit8 {
                        position[] = {-24,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AMGSPECIALIST";
                    };
                    class Unit9 {
                        position[] = {29,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit10 {
                        position[] = {-29,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit11 {
                        position[] = {34,-37,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit12 {
                        position[] = {-34,-37,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit13 {
                        position[] = {39,-42,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit14 {
                        position[] = {-39,-42,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_MECHSQUADBMP2 {
                    name = "Mechanized Squad (BMP-2)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {8,-12,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_BMP2";
                    };
                    class Unit2 {
                        position[] = {-8,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit3 {
                        position[] = {13,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AUTORIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-13,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_GRENADIER";
                    };
                    class Unit5 {
                        position[] = {18,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_DESIGMARKSMAN";
                    };
                    class Unit6 {
                        position[] = {-18,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit7 {
                        position[] = {23,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MGSPECIALIST";
                    };
                    class Unit8 {
                        position[] = {-23,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AMGSPECIALIST";
                    };
                    class Unit9 {
                        position[] = {28,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit10 {
                        position[] = {-28,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit11 {
                        position[] = {33,-37,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

                class TALAG_O_WNT_MECHSQUADMTLB {
                    name = "Mechanized Squad (MTLB)";
                    side = 0;
                    faction = "TALAG_O_WNT";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "TALAG_O_WNT_LEADER";
                    };
                    class Unit1 {
                        position[] = {8,-12,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MTLB";
                    };
                    class Unit2 {
                        position[] = {-8,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RTO";
                    };
                    class Unit3 {
                        position[] = {13,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_AUTORIFLEMAN";
                    };
                    class Unit4 {
                        position[] = {-13,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_GRENADIER";
                    };
                    class Unit5 {
                        position[] = {18,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_DESIGMARKSMAN";
                    };
                    class Unit6 {
                        position[] = {-18,-22,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_MEDIC";
                    };
                    class Unit7 {
                        position[] = {23,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_ATRIFLEMAN";
                    };
                    class Unit8 {
                        position[] = {-23,-27,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                    class Unit9 {
                        position[] = {28,-32,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "TALAG_O_WNT_RIFLEMAN";
                    };
                };

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};